// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVWh8_XSdRj8DnMmTBGImu0bnOWdK2vA',
    appId: '1:702827907269:web:445f414f64ae2ba2b708ac',
    messagingSenderId: '702827907269',
    projectId: 'smartchat-477f3',
    authDomain: 'smartchat-477f3.firebaseapp.com',
    storageBucket: 'smartchat-477f3.firebasestorage.app',
    measurementId: 'G-8XTN3Y85TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDa6NdPfLjZuN6FJutzuJZYR18hyCMvKk',
    appId: '1:702827907269:android:417289bdc071c52fb708ac',
    messagingSenderId: '702827907269',
    projectId: 'smartchat-477f3',
    storageBucket: 'smartchat-477f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolhTRWKl4ta6oG2zybl8sIQ-m4bdWgkg',
    appId: '1:702827907269:ios:6e86869d33878249b708ac',
    messagingSenderId: '702827907269',
    projectId: 'smartchat-477f3',
    storageBucket: 'smartchat-477f3.firebasestorage.app',
    iosClientId: '702827907269-7fbemom1mcumjk3h9g543os1991etagh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBolhTRWKl4ta6oG2zybl8sIQ-m4bdWgkg',
    appId: '1:702827907269:ios:6e86869d33878249b708ac',
    messagingSenderId: '702827907269',
    projectId: 'smartchat-477f3',
    storageBucket: 'smartchat-477f3.firebasestorage.app',
    iosClientId: '702827907269-7fbemom1mcumjk3h9g543os1991etagh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWVWh8_XSdRj8DnMmTBGImu0bnOWdK2vA',
    appId: '1:702827907269:web:e8b989df7677e3dbb708ac',
    messagingSenderId: '702827907269',
    projectId: 'smartchat-477f3',
    authDomain: 'smartchat-477f3.firebaseapp.com',
    storageBucket: 'smartchat-477f3.firebasestorage.app',
    measurementId: 'G-3VY8RQWSVW',
  );
}
